-- Migration: Fix create_price_request to assign initial approver
-- Auto-generated by Agent

-- 1. Update create_price_request to find and assign initial approver
CREATE OR REPLACE FUNCTION public.create_price_request(
    p_station_id text,
    p_product text,
    p_final_price numeric,
    p_margin_cents integer DEFAULT 0,
    p_client_id text DEFAULT NULL,
    p_payment_method_id text DEFAULT NULL,
    p_observations text DEFAULT NULL,
    p_status text DEFAULT 'pending',
    p_purchase_cost numeric DEFAULT 0,
    p_freight_cost numeric DEFAULT 0,
    p_cost_price numeric DEFAULT 0,
    p_batch_id uuid DEFAULT NULL,
    p_batch_name text DEFAULT NULL,
    p_volume_made numeric DEFAULT 0,
    p_volume_projected numeric DEFAULT 0,
    p_arla_purchase_price numeric DEFAULT 0,
    p_arla_cost_price numeric DEFAULT 0
)
RETURNS public.price_suggestions
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user_id uuid;
    v_new_request public.price_suggestions;
    v_cost_data record;
    v_purchase_cost numeric;
    v_freight_cost numeric;
    v_total_cost numeric;
    v_margin_cents integer := p_margin_cents;
    
    v_base_nome text := 'Manual';
    v_base_uf text := '';
    v_forma_entrega text := '';
    v_base_bandeira text := '';
    v_base_codigo text := '';

    v_initial_profile text;
    v_initial_approver record;
BEGIN
    v_user_id := auth.uid();
    
    -- Basic validation
    IF p_station_id IS NULL OR p_product IS NULL OR p_final_price IS NULL OR p_final_price <= 0 THEN
        RAISE EXCEPTION 'Missing required fields or invalid price: station_id, product, or final_price > 0';
    END IF;

    -- Initialize costs with passed values
    v_purchase_cost := p_purchase_cost;
    v_freight_cost := p_freight_cost;
    v_total_cost := p_cost_price;

    -- Try to fetch current costs from get_lowest_cost_freight to fill IF passed values are zero
    IF v_purchase_cost = 0 OR v_total_cost = 0 THEN
        BEGIN
            SELECT custo, frete, custo_total, base_nome, base_uf, forma_entrega, base_bandeira, base_codigo
            INTO v_cost_data
            FROM public.get_lowest_cost_freight(p_station_id, p_product)
            LIMIT 1;

            IF FOUND THEN
                v_purchase_cost := COALESCE(NULLIF(v_purchase_cost, 0), v_cost_data.custo);
                v_freight_cost := COALESCE(NULLIF(v_freight_cost, 0), v_cost_data.frete);
                v_total_cost := COALESCE(NULLIF(v_total_cost, 0), v_cost_data.custo_total);
                
                v_base_nome := COALESCE(v_cost_data.base_nome, 'Manual');
                v_base_uf := COALESCE(v_cost_data.base_uf, '');
                v_forma_entrega := COALESCE(v_cost_data.forma_entrega, '');
                v_base_bandeira := COALESCE(v_cost_data.base_bandeira, '');
                v_base_codigo := COALESCE(v_cost_data.base_codigo, '');
            END IF;
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Could not fetch lowest cost freight, using passed values';
        END;
    END IF;
        
    -- Recalculate margin in cents: (final_price - total_cost) * 100
    IF v_total_cost IS NOT NULL AND v_total_cost > 0 THEN
        v_margin_cents := ((p_final_price - v_total_cost) * 100)::integer;
    ELSE
        v_total_cost := COALESCE(v_total_cost, 0);
    END IF;

    -- FIND INITIAL APPROVER (Rule: Level 1)
    -- 1. Try to find configured profile for level 1
    SELECT perfil INTO v_initial_profile 
    FROM public.approval_profile_order 
    WHERE order_position = 1 AND is_active = true
    LIMIT 1;

    -- 2. Default to 'analista_pricing' if configuration missing
    v_initial_profile := COALESCE(v_initial_profile, 'analista_pricing');

    -- 3. Find an active user with this profile
    SELECT user_id, nome, email INTO v_initial_approver
    FROM public.user_profiles
    WHERE perfil = v_initial_profile AND ativo = true
    LIMIT 1;

    -- Insert request with enriched cost data AND initial approver
    INSERT INTO public.price_suggestions (
        station_id,
        product,
        final_price,
        purchase_cost,
        freight_cost,
        cost_price,
        margin_cents,
        suggested_price,
        client_id,
        payment_method_id,
        observations,
        status,
        created_by,
        price_origin_base,
        price_origin_uf,
        price_origin_delivery,
        price_origin_bandeira,
        price_origin_code,
        batch_id,
        batch_name,
        volume_made,
        volume_projected,
        arla_purchase_price,
        arla_cost_price,
        approval_level,
        approvals_count,
        total_approvers,
        current_approver_id,
        current_approver_name
    ) VALUES (
        p_station_id,
        p_product::public.product_type,
        p_final_price,
        v_purchase_cost,
        v_freight_cost,
        v_total_cost,
        v_margin_cents,
        p_final_price,
        p_client_id,
        p_payment_method_id,
        p_observations,
        p_status::public.approval_status,
        v_user_id,
        v_base_nome,
        v_base_uf,
        v_forma_entrega,
        v_base_bandeira,
        v_base_codigo,
        p_batch_id,
        p_batch_name,
        p_volume_made,
        p_volume_projected,
        p_arla_purchase_price,
        p_arla_cost_price,
        1,
        0,
        1,
        v_initial_approver.user_id,
        COALESCE(v_initial_approver.nome, v_initial_approver.email, 'Perfil: ' || v_initial_profile)
    ) RETURNING * INTO v_new_request;

    -- Notify Initial Approver
    IF v_initial_approver.user_id IS NOT NULL THEN
        INSERT INTO public.notifications (user_id, title, message, type, suggestion_id, read)
        VALUES (
            v_initial_approver.user_id,
            'Nova Solicitação',
            'Nova solicitação aguardando aprovação (Nível 1)',
            'approval_pending',
            v_new_request.id,
            false
        );
    END IF;

    RETURN v_new_request;
END;
$$;

-- 2. Fix existing pending requests with missing approvers
DO $$
DECLARE
    r record;
    v_approver record;
BEGIN
    -- Find default approver (Analista Pricing)
    SELECT user_id, nome, email INTO v_approver 
    FROM public.user_profiles 
    WHERE perfil = 'analista_pricing' AND ativo = true 
    LIMIT 1;

    IF v_approver.user_id IS NOT NULL THEN
        UPDATE public.price_suggestions
        SET current_approver_id = v_approver.user_id,
            current_approver_name = COALESCE(v_approver.nome, v_approver.email, 'Analista Pricing')
        WHERE status = 'pending' AND current_approver_id IS NULL;
        
        RAISE NOTICE 'Fixed missing approvers using user: %', v_approver.email;
    ELSE
        RAISE NOTICE 'Warning: No Analista Pricing found to fix existing requests.';
    END IF;
END $$;
